2013/02/05 09:51:42 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'praktik.tbl_users' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_users`.
in C:\xampp\htdocs\Yii\index.php (13)
2013/02/05 10:29:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\Yii\protected\controllers\UsersController.php:157
Stack trace:
#0 C:\xampp\htdocs\Yii\protected\controllers\UsersController.php(55): UsersController->loadModel('120')
#1 [internal function]: UsersController->actionView('120')
#2 C:\xampp\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 C:\xampp\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#4 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/view')
#14 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/Yii/index.php?r=users/view&id=120
HTTP_REFERER=http://localhost/Yii/index.php?r=users/create
---
2013/02/05 10:29:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\Yii\protected\controllers\UsersController.php:157
Stack trace:
#0 C:\xampp\htdocs\Yii\protected\controllers\UsersController.php(55): UsersController->loadModel('120')
#1 [internal function]: UsersController->actionView('120')
#2 C:\xampp\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 C:\xampp\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#4 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/view')
#14 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/Yii/index.php?r=users/view&id=120
HTTP_REFERER=http://localhost/Yii/index.php?r=users/create
---
2013/02/05 10:58:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "outbound".' in C:\xampp\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('outbound')
#1 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Yii/index.php?r=outbound
---
2013/02/05 10:59:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.php?".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('index.php?')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('index.php?')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.php?...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/index.php?/r=documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=documentsOutbound
---
2013/02/05 10:59:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.php?".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('index.php?')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('index.php?')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.php?...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/index.php?/r=documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=documentsOutbound
---
2013/02/05 10:59:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.php?r=documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('index.php?r=doc...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('index.php?r=doc...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.php?...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/index.php?r=documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/index.php?/r=documentsOutbound
---
2013/02/05 10:59:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.php?r=documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('index.php?r=doc...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('index.php?r=doc...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.php?...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/index.php?r=documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/index.php?/r=documentsOutbound
---
2013/02/05 10:59:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/index.php?r=documentsOutbound
---
2013/02/05 11:01:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/index.php?r=documentsOutbound
---
2013/02/05 11:01:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/index.php?r=documentsOutbound
---
2013/02/05 11:01:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/index.php?r=documentsOutbound
---
2013/02/05 11:01:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/documentsOutbound
---
2013/02/05 11:02:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/documentsOutbound
---
2013/02/05 11:02:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/documentsOutbound
---
2013/02/05 11:02:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbounddocumentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbounddocumentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/documentsOutbound
---
2013/02/05 11:02:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbounddocumentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbounddocumentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/documentsOutbounddocumentsOutbound
---
2013/02/05 11:02:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbounddocumentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbounddocumentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/documentsOutbounddocumentsOutbound
---
2013/02/05 11:02:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbounddocumentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbounddocumentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/documentsOutbounddocumentsOutbound
---
2013/02/05 11:02:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/documentsOutbounddocumentsOutbound
---
2013/02/05 11:02:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/documentsOutbounddocumentsOutbound
---
2013/02/05 11:08:07 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('view')
#9 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('documentsinboun...')
#10 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/Yii/index.php?r=documentsinbound/view
HTTP_REFERER=http://localhost/Yii/index.php?r=site/index
---
2013/02/05 11:08:24 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('view')
#9 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('documentsinboun...')
#10 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/Yii/index.php?r=documentsinbound/view
HTTP_REFERER=http://localhost/Yii/index.php?r=site/index
---
